### PR TITLE
Add FormMessage component

### LINKED ISSUE #65: Add FormError component
Design #57.

### PR DESCRIPTION
**Pull request by paulocfjunior**
Closes #65.

image

### CODE REVIEW

**Comment by paulocfjunior** [comment]
Adding to the Docs.

**Comment by paulocfjunior** [comment]
@matthieuh I renamed it to FormMessage because it's generic enough to be used with any color or icon. Is that okay? Do you have another suggestion for the name?

**Comment by matthieuh** [comment]
@paulocfjunior FormMessage seems good to me!

**Comment by paulocfjunior** [comment]
#### Documentation preview

image

**Pull request merged**
