### PR TITLE
Add Dropdown and Menu components

### PR DESCRIPTION
**Pull request by paulocfjunior**
Added a separated Menu component once it can be used on other use cases as well.
Also fixed all the unit tests to support the theme context, and added the test run to the CI.

### CODE REVIEW

**Comment by paulocfjunior** [comment]
Hey @matthieuh, I tried to reuse the Radix Menu component for the InputTags component, as autocomplete, but I couldn't get the arrow navigation to work at all. Do you have any idea how we could handle that?

**Comment by matthieuh** [comment]
@paulocfjunior I also tried a bit on your PR but I didn't found a way. Btw Could you think of adding docs for all new components?

**Comment by paulocfjunior** [comment]
For some reason, the components `MenuItemRadio`, `MenuItemRadioGroup`, `MenuItemSeparator` and `MenuItemLabel` are not rendering on the Docs website (they work on the Storybook though), and the Menu's `onDismiss` callback is not working at all, neither on their documentation, that describes it as `onClose` but this prop actually doesn't exist on the component.

Trying to find a solution to this, but no luck so far.

**Comment by paulocfjunior** [comment]
@matthieuh I extracted the test changes to another [pull request](https://github.com/containous/faency/pull/90) and the documentation issue with MenuItems is gone, now it doesn't work only on the unit tests.

**Pull request merged**
